version: 0.0
os: linux
files:
  - sources: /
    destination: /home/ec2-user/app/jenkins
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: scripts/jenkinsDeploy.sh    # ApplicationStart 단계에서 해당 파일을 실행해라
      timeout: 60
      runas: ec2-user